### ISSUE TITLE
[bug]  have to quickly turn off and on gc to boot into swiss from mem card b

### ISSUE THREAD

**Issue by jazzpunkshit** [OffBroadway/cubeboot#32] opened 2023-08-02 18:46 UTC
saw someone post something similar and have tried putting cubeboot directly onto my pico to see if it would make a difference but sadly it has not. 

i get the message:

iplboot
trying sdb
couldn't mount sdb: device not ready
trying sda
couldn't mount sdb: device not ready
trying sd2
couldn't mount sd2: device not ready
no dol loaded. rebooting into original ipl...

it seems to get stuck there so if i reboot quickly it boots swiss
it seems to be reading my ini given the boot color is what i set it to and my png is loading so i'm unsure of what the issue is really
unless it has something to do with the gamecube hardware and it prioritizing mem slot a or something.

**Comment by kainstroke** [comment] 2023-08-30 02:17
I'm getting the same issue

**Comment by trevor403** [comment] 2023-09-23 03:29
Closing as a duplicate of #17

**Closed by trevor403** 2023-09-23 03:29 UTC
Labels: bug
